#!/bin/bash
# Rebuild FFmpeg with shared DLLs (required for mpv to use custom codecs)
# FFmpeg -  ♥♥ Alternative Development Broadcast Edition ♥♥ - 8.1.2
# This produces DLLs that must be bundled alongside the executables

set -e

LOG_FILE="${FFMPEG_BUILD_LOG:-build-msys-shared.log}"
: > "$LOG_FILE"
exec > >(tee -a "$LOG_FILE") 2>&1

FFMPEG_PREFIX="${FFMPEG_PREFIX:-./build}"
FFMPEG_BIN="$FFMPEG_PREFIX/bin"
BASISU_ROOT="${BASISU_ROOT:-$PWD/thirdparty/basis_universal}"
BASISU_CFLAGS=""
BASISU_LDFLAGS=""
BASISU_LIBS=""

if [ -f "$BASISU_ROOT/build_mingw/libbasisu_encoder.a" ]; then
    BASISU_CFLAGS="-I$BASISU_ROOT/encoder -I$BASISU_ROOT/transcoder -I$BASISU_ROOT"
    BASISU_LDFLAGS="-L$BASISU_ROOT/build_mingw"
    BASISU_LIBS="-lbasisu_encoder -lstdc++ -lpthread"
    echo "basis_universal found: $BASISU_ROOT/build_mingw/libbasisu_encoder.a"
else
    echo "ERROR: basis_universal not built. Run ./build-msys-prepare-basis-universal.sh first."
    exit 1
fi

BINK2SDK_ROOT="${BINK2SDK_ROOT:-$PWD/thirdparty/bink2sdk}"
BINK2SDK_CFLAGS=""
BINK2SDK_LDFLAGS=""
BINK2SDK_LIBS=""

if [ -f "$BINK2SDK_ROOT/build_mingw/libbink2sdk.a" ]; then
    BINK2SDK_CFLAGS="-I$BINK2SDK_ROOT/src"
    BINK2SDK_LDFLAGS="-L$BINK2SDK_ROOT/build_mingw"
    BINK2SDK_LIBS="-lbink2sdk"
    echo "bink2sdk found: $BINK2SDK_ROOT/build_mingw/libbink2sdk.a"
else
    echo "WARNING: bink2sdk not built. Bink2 decoder will use built-in (no deblocking)."
    echo "  Run ./build-msys-prepare-bink2sdk.sh to build it."
fi

NDISDK_ROOT="${NDISDK_ROOT:-$PWD/thirdparty/ndisdk}"
NDISDK_CFLAGS=""
NDISDK_LDFLAGS=""
NDISDK_ENABLE=""

if [ -f "$NDISDK_ROOT/include/Processing.NDI.Lib.h" ] && \
   { [ -f "$NDISDK_ROOT/build_mingw/libndi.dll.a" ] || [ -f "$NDISDK_ROOT/build_mingw/libndi.a" ]; }; then
    NDISDK_CFLAGS="-I$NDISDK_ROOT/include"
    NDISDK_LDFLAGS="-L$NDISDK_ROOT/build_mingw"
    NDISDK_ENABLE="--enable-libndi_newtek"
    echo "NDI SDK found: $NDISDK_ROOT (libndi_newtek enabled)"
else
    echo "WARNING: NDI SDK not prepared. NDI input/output devices disabled."
    echo "  Run ./build-msys-prepare-ndisdk.sh to enable them."
fi

DECKLINK_ROOT="${DECKLINK_ROOT:-$PWD/thirdparty/decklinksdk}"
DECKLINK_CFLAGS=""
DECKLINK_ENABLE=""

# DeckLink is COM: headers only (generated by widl), no import lib, no bundled
# DLL. configure adds -lole32 -loleaut32 on Windows on its own.
if [ -f "$DECKLINK_ROOT/include/DeckLinkAPI.h" ] && \
   [ -f "$DECKLINK_ROOT/include/DeckLinkAPI_i.c" ]; then
    DECKLINK_CFLAGS="-I$DECKLINK_ROOT/include"
    DECKLINK_ENABLE="--enable-decklink"
    echo "DeckLink SDK found: $DECKLINK_ROOT (decklink enabled)"
else
    echo "WARNING: DeckLink SDK not prepared. Blackmagic devices disabled."
    echo "  Run ./build-msys-prepare-decklinksdk.sh to enable them."
fi

# libplacebo (MSYS2 package): Vulkan renderer with alpha support and mpv
# .hook custom shaders (CNN super-resolution: FSRCNNX, Anime4K, RAVU...).
# The shaders themselves are runtime text files bundled in bin/shaders/.
PLACEBO_ENABLE=""
if pkg-config --exists "libplacebo >= 5.229.0" 2>/dev/null; then
    PLACEBO_ENABLE="--enable-libplacebo"
    echo "libplacebo found: $(pkg-config --modversion libplacebo) (libplacebo filter enabled)"
else
    echo "WARNING: libplacebo not installed. libplacebo filter disabled."
    echo "  pacman -S mingw-w64-x86_64-libplacebo (or ./build-msys-install-dependencies.sh)"
fi

SHADERS_ROOT="${SHADERS_ROOT:-$PWD/thirdparty/shaders}"
if ls "$SHADERS_ROOT"/*.glsl >/dev/null 2>&1; then
    echo "SR shaders found: $SHADERS_ROOT (bundled in bin/shaders/)"
else
    echo "WARNING: SR shaders not downloaded. Run ./build-msys-prepare-shaders.sh"
    echo "  to bundle FSRCNNX / Anime4K / RAVU next to ffmpeg.exe."
fi

# NVIDIA RTX Video SDK (VSR): reached through the MSVC shim rtxvsr.dll built
# by build-msys-prepare-rtxvideosdk.sh. Only the shim header is needed at
# configure time; the DLLs are loaded at runtime by the sr_rtx filter.
RTXVSR_ROOT="${RTXVSR_ROOT:-$PWD/thirdparty/rtxvsr}"
RTXVSR_CFLAGS=""
RTXVSR_ENABLE=""
if [ -f "$RTXVSR_ROOT/include/rtxvsr.h" ] && \
   [ -f "$RTXVSR_ROOT/build_mingw/rtxvsr.dll" ] && \
   [ -f "$RTXVSR_ROOT/build_mingw/nvngx_vsr.dll" ]; then
    RTXVSR_CFLAGS="-I$RTXVSR_ROOT/include"
    RTXVSR_ENABLE="--enable-librtxvsr"
    echo "RTX VSR shim found: $RTXVSR_ROOT (sr_rtx filter enabled)"
else
    echo "WARNING: RTX Video SDK shim not built. sr_rtx filter disabled."
    echo "  Run ./build-msys-prepare-rtxvideosdk.sh to enable it."
fi

echo "=========================================="
echo "FFmpeg -  ♥♥ Alternative Development Broadcast Edition ♥♥ - 8.1.2"
echo "Rebuilding with SHARED DLLs (mpv-compatible)"
echo "=========================================="
echo ""

echo "Step 1: Cleaning previous build..."
make clean 2>/dev/null || true
rm -f config.h config.log ffbuild/config.mak 2>/dev/null || true
rm -rf "$FFMPEG_PREFIX" 2>/dev/null || true
rm -f ./*.dll 2>/dev/null || true

echo ""
echo "Step 2: Configuring build options (SHARED BUILD):"
echo "  - Core: --enable-gpl --enable-version3 --enable-nonfree --disable-debug"
echo "  - Link: --enable-shared --disable-static"
echo "  - Video: --enable-libx264 --enable-libx265 --enable-libvpx --enable-libaom --enable-libsvtav1 --enable-libdav1d --enable-libzimg"
echo "  - Audio: --enable-libvorbis --enable-libopus --enable-libmp3lame --enable-libfdk-aac"
echo "  - HAP: --enable-libsnappy + basis_universal (BC7/BC6H static link)"
echo "  - Vulkan: --enable-vulkan --enable-libshaderc"
echo "  - libplacebo (SR shaders): ${PLACEBO_ENABLE:-disabled (pacman -S mingw-w64-x86_64-libplacebo)}"
echo "  - RTX VSR (sr_rtx): ${RTXVSR_ENABLE:-disabled (run ./build-msys-prepare-rtxvideosdk.sh)}"
echo "  - Network: --enable-libsrt --enable-openssl"
echo "  - NDI: ${NDISDK_ENABLE:-disabled (run ./build-msys-prepare-ndisdk.sh)}"
echo "  - DeckLink: ${DECKLINK_ENABLE:-disabled (run ./build-msys-prepare-decklinksdk.sh)}"
echo "  - Hardware Decode: --enable-d3d11va --enable-d3d12va"
echo "  - CFLAGS: -O3 $BASISU_CFLAGS"
echo ""

# Preflight: show which x265 will be used
echo "Step 2.5: Preflight x265 check..."
if command -v pkg-config >/dev/null 2>&1; then
    if pkg-config --exists x265; then
        echo "✓ pkg-config x265 version: $(pkg-config --modversion x265)"
        echo "✓ pkg-config x265 libs: $(pkg-config --libs x265)"
        echo "✓ pkg-config x265 cflags: $(pkg-config --cflags x265)"
    else
        echo "⚠️  pkg-config cannot find x265"
    fi
else
    echo "⚠️  pkg-config not found"
fi
if command -v /mingw64/bin/x265 >/dev/null 2>&1; then
    /mingw64/bin/x265 --help 2>/dev/null | grep -qi -- "--alpha" \
        && echo "✓ /mingw64/bin/x265 reports alpha support" \
        || echo "⚠️  /mingw64/bin/x265 does not mention alpha"
    # A 10-bit-only x265 accepts yuva420p but fills the alpha layer with the
    # base luma (x265 only implements the 8-bit alpha input path at
    # X265_DEPTH == 8). Multilib is what makes 8-bit alpha correct.
    /mingw64/bin/x265 --version 2>&1 | grep -q "8bit+10bit+12bit" \
        && echo "✓ /mingw64/bin/x265 is a 8+10+12 bit multilib" \
        || echo "⚠️  /mingw64/bin/x265 is NOT multilib - 8-bit HEVC alpha will be wrong (run ./build-msys-prepare-x265-with-alpha.sh)"
else
    echo "⚠️  /mingw64/bin/x265 not found"
fi
echo ""

# Note: Shared build is required so mpv can load custom FFmpeg codecs.
# Note: --disable-w32threads --enable-pthreads is REQUIRED for DeckLink.
# DeckLink devices are C++ (decklink_*.cpp) and pull in libavutil/thread.h;
# the default w32threads path (compat/w32pthreads.h) is not C++-safe (its
# `pthread_t` typedef clashes with the struct tag under C++), so we force
# winpthreads. Both flags are needed: w32threads is autodetect-enabled by
# default, and --enable-pthreads alone skips the block that would turn it off,
# leaving w32threads on and making configure die "pthreads requested but not
# found". Disabling w32threads explicitly lets pthreads detection run.
./configure \
    --enable-gpl \
    --enable-version3 \
    --enable-nonfree \
    --disable-debug \
    --enable-shared \
    --disable-static \
    --disable-w32threads \
    --enable-pthreads \
    --prefix="$FFMPEG_PREFIX" \
    --enable-zlib \
    --enable-libsnappy \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libvpx \
    --enable-libaom \
    --enable-libsvtav1 \
    --enable-libdav1d \
    --enable-libvorbis \
    --enable-libopus \
    --enable-libmp3lame \
    --enable-libfdk-aac \
    --enable-libzimg \
    --enable-libsrt \
    --enable-openssl \
    --enable-vulkan \
    --enable-libshaderc \
    --enable-d3d11va \
    --enable-d3d12va \
    $NDISDK_ENABLE \
    $DECKLINK_ENABLE \
    $PLACEBO_ENABLE \
    $RTXVSR_ENABLE \
    --extra-cflags="-O3 $BASISU_CFLAGS $BINK2SDK_CFLAGS $NDISDK_CFLAGS $DECKLINK_CFLAGS $RTXVSR_CFLAGS" \
    --extra-cxxflags="-O3 $DECKLINK_CFLAGS" \
    --extra-ldflags="$BASISU_LDFLAGS $BINK2SDK_LDFLAGS $NDISDK_LDFLAGS" \
    --extra-libs="$BASISU_LIBS $BINK2SDK_LIBS"

echo ""
echo "Step 3: Verifying HAP and Bink2 are enabled..."
grep -q "CONFIG_HAP_ENCODER=yes" ffbuild/config.mak && echo "✓ HAP encoder enabled" || echo "✗ HAP encoder NOT enabled"
grep -q "CONFIG_HAP_DECODER=yes" ffbuild/config.mak && echo "✓ HAP decoder enabled" || echo "✗ HAP decoder NOT enabled"
grep -q "CONFIG_BINK2_DECODER=yes" ffbuild/config.mak && echo "✓ Bink2 decoder enabled" || echo "✗ Bink2 decoder NOT enabled"

echo ""
echo "Step 4: Building FFmpeg..."
CPU_CORES=$(nproc)
echo "Using $CPU_CORES CPU cores..."
make -j$CPU_CORES

echo ""
echo "Step 5: Installing to $FFMPEG_PREFIX..."
make install

echo ""
echo "Step 6: basis_universal is statically linked, no runtime DLL needed."

echo ""
echo "=========================================="
echo "✓ Build Complete!"
echo "=========================================="
echo ""
echo "FFmpeg -  ♥♥ Alternative Development Broadcast Edition ♥♥ - 8.1.2"
echo "Build type: SHARED DLLs (bundle required)"
echo "Build features:"
echo "  - Hap R support (FourCC: 'Hap7') - BC7 via basis_universal"
echo "  - Hap H support (FourCC: 'HapH') - BC6H via basis_universal"
echo "  - HapM support (FourCC: 'HapM')"
echo "  - HapA support (FourCC: 'HapA')"
echo "  - Fixed YCoCg color transform"
echo "  - Bink video 2 decoder (binkvideo2)"
echo "  - ProRes encoder (prores, prores_aw, prores_ks)"
echo ""

# Check built executables
echo "Built executables:"
ls -lh "$FFMPEG_BIN/ffmpeg.exe" "$FFMPEG_BIN/ffplay.exe" "$FFMPEG_BIN/ffprobe.exe" 2>/dev/null | awk '{print "  " $9 " (" $5 ")"}'

echo ""
echo "Step 7: Bundling required DLLs..."
echo ""

# Copy required MINGW64 DLLs to the install bin dir.
# ldd resolves DLLs through the PATH, so an older bundle elsewhere on the PATH
# (tools/ffmpeg of nnTools, AdFlocon...) would shadow /mingw64/bin, get
# filtered out by the mingw64 grep and never be copied - which is how a stale
# libvpx 1.15 ended up next to an FFmpeg built against 1.17 ("ABI version
# mismatch"). Force /mingw64/bin first, scan recursively (exes + DLLs already
# copied) and overwrite whatever differs from MINGW64.
DLL_COUNT=0
pass=0
added=1
while [ "$added" -ne 0 ] && [ "$pass" -lt 10 ]; do
    added=0
    pass=$((pass + 1))
    REQUIRED_DLLS=$(cd "$FFMPEG_BIN" && PATH="/mingw64/bin:$PATH" ldd ./*.exe ./*.dll 2>/dev/null \
                    | grep -i mingw64 | awk '{print $3}' | sort -u) || true
    for dll in $REQUIRED_DLLS; do
        [ -f "$dll" ] || continue
        target="$FFMPEG_BIN/$(basename "$dll")"
        if [ ! -f "$target" ] || ! cmp -s "$dll" "$target"; then
            cp -v "$dll" "$target"
            DLL_COUNT=$((DLL_COUNT + 1))
            added=$((added + 1))
        fi
    done
done

echo ""
echo "✓ Bundled $DLL_COUNT DLLs from MINGW64 ($pass pass(es))"
echo ""

# NDI runtime DLL is not a mingw64 DLL, bundle it explicitly
if [ -n "$NDISDK_ENABLE" ] && [ -f "$NDISDK_ROOT/build_mingw/Processing.NDI.Lib.x64.dll" ]; then
    cp -v "$NDISDK_ROOT/build_mingw/Processing.NDI.Lib.x64.dll" "$FFMPEG_BIN/"
    echo "✓ Bundled NDI runtime DLL"
    echo ""
fi

# RTX VSR: the MSVC shim and the NVIDIA runtime it needs, both loaded at
# runtime from the executable directory.
if [ -n "$RTXVSR_ENABLE" ]; then
    cp -v "$RTXVSR_ROOT/build_mingw/rtxvsr.dll" "$FFMPEG_BIN/"
    cp -v "$RTXVSR_ROOT/build_mingw/nvngx_vsr.dll" "$FFMPEG_BIN/"
    echo "✓ Bundled RTX VSR runtime DLLs"
    echo ""
fi

# Super-resolution shaders for the libplacebo filter (custom_shader_path).
if ls "$SHADERS_ROOT"/*.glsl >/dev/null 2>&1; then
    rm -rf "$FFMPEG_BIN/shaders"
    mkdir -p "$FFMPEG_BIN/shaders"
    cp -r "$SHADERS_ROOT"/. "$FFMPEG_BIN/shaders/"
    echo "✓ Bundled SR shaders in $FFMPEG_BIN/shaders ($(find "$FFMPEG_BIN/shaders" -type f \( -name '*.glsl' -o -name '*.hook' \) | wc -l) files)"
    echo ""
fi

echo "Testing HAP encoder:"
"$FFMPEG_BIN/ffmpeg" -hide_banner -encoders 2>/dev/null | grep hap || echo "HAP not found in encoders"

echo ""
echo "Testing Bink2 decoder:"
"$FFMPEG_BIN/ffmpeg" -hide_banner -decoders 2>/dev/null | grep binkvideo2 || echo "Bink2 not found in decoders"

echo ""
echo "Testing ProRes encoder:"
"$FFMPEG_BIN/ffmpeg" -hide_banner -encoders 2>/dev/null | grep prores || echo "ProRes not found in encoders"

if [ -n "$NDISDK_ENABLE" ]; then
    echo ""
    echo "Testing NDI devices:"
    "$FFMPEG_BIN/ffmpeg" -hide_banner -devices 2>/dev/null | grep libndi_newtek || echo "NDI not found in devices"
fi

if [ -n "$DECKLINK_ENABLE" ]; then
    echo ""
    echo "Testing DeckLink devices:"
    "$FFMPEG_BIN/ffmpeg" -hide_banner -devices 2>/dev/null | grep decklink || echo "DeckLink not found in devices"
fi

if [ -n "$PLACEBO_ENABLE" ]; then
    echo ""
    echo "Testing libplacebo filter:"
    "$FFMPEG_BIN/ffmpeg" -hide_banner -filters 2>/dev/null | grep -w libplacebo || echo "libplacebo not found in filters"
fi

if [ -n "$RTXVSR_ENABLE" ]; then
    echo ""
    echo "Testing sr_rtx filter:"
    "$FFMPEG_BIN/ffmpeg" -hide_banner -filters 2>/dev/null | grep -w sr_rtx || echo "sr_rtx not found in filters"
fi

echo ""
echo "=========================================="
echo "♥♥ Alternative Development Broadcast Edition ♥♥ - 8.1.2"
echo "Portable Build Complete"
echo "=========================================="
echo ""
echo "Files in $FFMPEG_BIN (executables + DLLs):"
ls -lh "$FFMPEG_BIN"/*.exe "$FFMPEG_BIN"/*.dll 2>/dev/null | awk '{print "  " $9 " (" $5 ")"}'
echo ""
echo "These files can be copied together to any location"
echo "and will work from PowerShell, CMD, and Python apps"
echo "without requiring MSYS2."
echo ""
echo "To deploy to your app, use:"
echo "  ./build-msys-copy-with-dlls-shared.sh"
echo ""
echo "Run it now? (Y/n)"
read -r RUN_COPY
RUN_COPY=${RUN_COPY:-Y}
if [ -z "$RUN_COPY" ] || [ "$RUN_COPY" = "y" ] || [ "$RUN_COPY" = "Y" ]; then
    ./build-msys-copy-with-dlls-shared.sh
fi
echo ""
